### PR TITLE
Update to slapdash@1

### PR DESCRIPTION
**Pull request by jimmed**

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @oliverwoodings to be a potential reviewer

**Comment by jimmed** [comment]
CI build is failing due to SauceLab heartbeat timeouts in Safari. I'm skeptical as to whether this is our problem, or Safari being a dick.

**Comment by jimmed** [comment]
Genuinely no idea how to get this CI build to pass. Mostly just saucelabs timing out.

**Comment by oliverwoodings** [comment]
I got the tests to pass now

**Comment by oliverwoodings** [comment]
Released

**Pull request merged**
