### PR TITLE
Use JSON Bourne for great justice

### PR DESCRIPTION
**Pull request by jimmed**

### CODE REVIEW

**Comment by swagatha-christie** [comment]
By analyzing the blame information on this pull request, we identified @oliverwoodings to be a potential reviewer

**Comment by oliverwoodings** [comment]
LGTM! Could you also check to see if this change needs to go into @alanclarke 's #27 PR? It's a fairly large refactor.

**Comment by jimmed** [comment]
Shall do!

**Comment by jimmed** [comment]
Just double-checked @alanclarke 's PR, and he doesn't seem to touch this file at all. Merging!

**Comment by oliverwoodings** [comment]
Awesome! I'll give you publishing rights on npm

**Comment by matt-ball** [comment]
Thanks both! Can you let me know when this is done/I'm in a position where I can republish the property?

**Comment by jimmed** [comment]
@matt-ball Published about 15 mins ago ;)

**Comment by matt-ball** [comment]
Cheers!

**Pull request merged**
